//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITstudy
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainingcentre
    {
        public int studentid { get; set; }
        public string studentname { get; set; }
        public string course { get; set; }
        public string durationofcourse { get; set; }
        public Nullable<int> fee { get; set; }
        public string batchname { get; set; }
        public string sex { get; set; }
        public Nullable<int> enrollmentno { get; set; }
        public string city { get; set; }
    }
}
